author: Teckchun Aing
email: teckchunaing@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my github page!

# social links
twitter_username: teckchun123
github_username:  teckchun

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
